name: Clean_Code_NumberTrivia
description: Number Trivia App with Resso's Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^3.0.6
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  equatable: ^1.2.6
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get: ^3.24.0
  hive: ^1.4.4+1
  json_annotation: ^3.1.1
  kiwi: ^2.1.1
  lint: ^1.3.0
  path_provider: ^1.6.27
  retrofit: ^1.3.4+1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  chopper_generator: ^3.0.6
  effective_dart: ^1.3.0
  freezed: ^0.12.7
  hive_flutter: ^0.3.1
  json_serializable: ^3.5.1
  kiwi_generator: ^2.1.1
  retrofit_generator: ^1.4.1+2

flutter:
  uses-material-design: true
