name: Clean_Code_NumberTrivia
description: Number Trivia App with Resso's Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^6.1.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^5.0.3
  equatable: ^1.2.6
  flutter_bloc: ^6.1.1
  freezed_annotation: ^2.2.0
  get: ^3.24.0
  hive: ^1.6.0-nullsafety.2
  json_annotation: ^4.8.0
  kiwi: ^4.1.0
  lint: ^1.3.0
  path_provider: ^1.6.27
  retrofit: ^4.0.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  effective_dart: ^1.3.0
  freezed: ^2.3.2
  hive_flutter: ^0.3.1
  json_serializable: ^6.6.1
  kiwi_generator: ^4.1.0
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
